#!/bin/bash
echo "Starting Pepin OS Tests..."
echo ""

# Test 1: Boot the system
echo "=== TEST 1: Boot Test ==="
echo "Run: qemu-system-i386 -kernel /app/kernel"
echo ""
echo "Expected output:"
echo "- Boot messages"
echo "- 'hello.elf created in filesystem' message"
echo "- 'calc.elf created in filesystem' message"
echo "- 'Pepin OS Shell v1.0' message"
echo "- 'pepin$ ' prompt"
echo ""
echo "Press ENTER to continue to file operations test..."
read

echo "=== TEST 2: File Operations Test ==="
echo "In the QEMU window, type these commands:"
echo ""
echo "Command 1: create test.txt 100"
echo "Expected: 'File created: test.txt'"
echo ""
echo "Command 2: write test.txt \"Hello World\""
echo "Expected: 'Text written to test.txt'"
echo ""
echo "Command 3: cat test.txt"
echo "Expected: 'Hello World' (THIS WAS BROKEN BEFORE - now fixed!)"
echo ""
echo "Press ENTER to continue to ELF test..."
read

echo "=== TEST 3: ELF Execution Test ==="
echo "In the QEMU window, type these commands:"
echo ""
echo "Command 1: ls"
echo "Expected: Should show hello.elf and calc.elf in the file listing"
echo ""
echo "Command 2: exec hello.elf"
echo "Expected: 'Hello from user program!' and 'This is a simple ELF program running in Pepin OS.'"
echo ""
echo "Command 3: exec calc.elf"
echo "Expected: Calculator output with math operations"
echo ""
echo "All tests completed!"
